include: sound: missing include
error: field has incomplete type 'struct timespec'

Change-Id: I8e6a42776450806d5cbb3e7c0b70b08820196757
Signed-off-by: mracar07 <umutcan@umutcanacar.me>